### ISSUE TITLE
After reboot, ri.tone_bins should be None but is np.array(None)

### ISSUE THREAD

**Issue by danielflanigan** [ColumbiaCMB/kid_readout#19]
After accidentally rebooting the roach, I reprogrammed it using initialize(use_config=False) then saved the state. Using this saved state, ri.get_state() fails:
```python
Traceback (most recent call last):
  File "r2b_coarse_fine_stream_3_resonators.py", line 49, in <module>
    f_resolution_coarse = ri.state.adc_sample_rate / num_tone_samples_coarse
  File "/home/flanigan/kid_readout/kid_readout/roach/interface.py", line 225, in state
    return self.get_state()
  File "/home/flanigan/kid_readout/kid_readout/roach/interface.py", line 232, in get_state
    num_tones=self.num_tones,
  File "/home/flanigan/kid_readout/kid_readout/roach/interface.py", line 188, in num_tones
    num_tones = self.tone_bins.shape[1] # We may want to update this later if some tones have
IndexError: tuple index out of range
```
I copied the state file to `/data/readout/roach_config_problem_2016-07-22.npz`.

Using a new roach object with this saved state:
```python
In [12]: ri.tone_bins
Out[12]: array(None, dtype=object)
```

**Comment by danielflanigan** [comment]
FWIW I'm now reprogramming the roach without using saved state by default in all measurement scripts, which avoids this problem.
